import { MODELS_CONFIG } from "../facebook.const";

export const PAGE_FIELDS = [
  "about",
  "access_token",
  "bio",
  "business",
  // "can_checkin",
  // "can_post",
  "category_list",
  "category",
  // "checkins",
  "company_overview",
  "country_page_likes",
  // "cover",
  "current_location",
  // "delivery_and_pickup_option_info",
  "description",
  // "differently_open_offerings",
  // "display_subtext",
  // "displayed_message_response_time",
  // "engagement",
  // "fan_count",
  // "featured_video",
  // "followers_count",
  "general_info",
  "global_brand_page_name",
  "global_brand_root_id",
  "has_transitioned_to_new_page_experience",
  // "has_whatsapp_business_number",
  // "hours",
  "id",
  // "impressum",
  // "is_chain",
  // "is_community_page",
  // "is_eligible_for_branded_content",
  // "is_eligible_for_disable_connect_ig_btn_for_non_page_admin_am_web",
  // "is_messenger_bot_get_started_enabled",
  // "is_messenger_platform_bot",
  // "is_owned",
  // "is_permanently_closed",
  // "is_published",
  // "is_unclaimed",
  // "is_webhooks_subscribed",
  // "leadgen_tos_acceptance_time",
  // "leadgen_tos_accepted",
  // "leadgen_tos_accepting_user",
  "link",
  "location",
  "name_with_location_descriptor",
  "name",
  "network",
  // "new_like_count",
  // "offer_eligible",
  "overall_star_rating",
  "parent_page",
  "parking",
  "phone",
  // "pickup_options",
  // "place_type",
  // "plot_outline",
  // "price_range",
  // "rating_count",
  // "record_label",
  // "schedule",
  // "season",
  "single_line_address",
  "starring",
  // "start_info",
  "store_code",
  "store_location_descriptor",
  "store_number",
  // "talking_about_count",
  // "temporary_status",
  // "unread_message_count",
  // "unread_notif_count",
  // "unseen_message_count",
  // "verification_status",
  // "voip_info",
  "website",
  // "were_here_count",
];

export const AD_ACCOUNT_FIELDS = [
  "account_status",
  "age",
  "amount_spent",
  "business_name",
  "currency",
  "created_time",
  "owner",
  "spend_cap",
  "timezone_name",
  "is_personal",
  "name",
];

export const BUSINESS_MODELS_CONFIG:MODELS_CONFIG = {
  pages: {
    edge: ["owned_pages","client_pages"],
    // edge: "owned_pages",
    get_fields: ["id", "name", "access_token"],
    fields: PAGE_FIELDS,
    fields_type: "fields",
    dependencies: ["page_insights","page_posts"],
  },
  ad_accounts: {
    edge: ["owned_ad_accounts","client_ad_accounts"],
    get_fields: ["id", "name", "account_id"],
    fields: AD_ACCOUNT_FIELDS,
    fields_type: "fields",
    // dependencies: ["campaigns"],
  },
};
