import { MODELS_CONFIG } from "../facebook.const";

const PAGE_METRICS = {
  page_cta_clicks: [
    "page_call_phone_clicks_logged_in_unique",
    "page_cta_clicks_logged_in_total",
    "page_cta_clicks_logged_in_unique",
    "page_get_directions_clicks_logged_in_unique",
    "page_total_actions",
    "page_website_clicks_logged_in_unique",
  ],
  page_engagements: [
    "page_consumptions_by_consumption_type_unique",
    "page_consumptions_by_consumption_type",
    "page_consumptions_unique",
    "page_daily_follows_unique",
    "page_daily_follows",
    "page_daily_unfollows_unique",
    "page_fan_adds_by_paid_non_paid_unique",
    "page_fans_online",
    "page_follows",
    "page_lifetime_engaged_followers_unique",
    "page_negative_feedback_by_type_unique",
    "page_negative_feedback_by_type",
    "page_negative_feedback_unique",
    "page_negative_feedback",
    "page_places_checkin_total_unique",
    "page_places_checkin_total",
    "page_post_engagements",
  ],
  page_impressions: [
    "page_impressions_by_age_gender_unique",
    "page_impressions_by_city_unique",
    "page_impressions_by_country_unique",
    "page_impressions_by_locale_unique",
    "page_impressions_by_story_type_unique",
    "page_impressions_by_story_type",
    "page_impressions_nonviral_unique",
    "page_impressions_nonviral",
    "page_impressions_organic_unique_v2",
    "page_impressions_organic_v2",
    "page_impressions_paid_unique",
    "page_impressions_paid",
    "page_impressions_unique",
    "page_impressions_viral_frequency_distribution",
    "page_impressions_viral_unique",
    "page_impressions_viral",
    "page_impressions",
    "page_views_total",
  ],
  page_posts: [
    "page_posts_impressions_nonviral_unique",
    "page_posts_impressions_nonviral",
    "page_posts_impressions_organic_unique",
    "page_posts_impressions_organic",
    "page_posts_impressions_paid_unique",
    "page_posts_impressions_paid",
    "page_posts_impressions_unique",
    "page_posts_impressions_viral_unique",
    "page_posts_impressions_viral",
    "page_posts_impressions",
    "page_posts_served_impressions_organic_unique",
  ],
  page_reactions: [
    "page_actions_post_reactions_anger_total",
    "page_actions_post_reactions_haha_total",
    "page_actions_post_reactions_like_total",
    "page_actions_post_reactions_love_total",
    "page_actions_post_reactions_sorry_total",
    "page_actions_post_reactions_total",
    "page_actions_post_reactions_wow_total",
  ],
  page_user_demographic: [
    "page_fan_adds_unique",
    "page_fan_adds",
    "page_fan_removes_unique",
    "page_fan_removes",
    "page_fans_city",
    "page_fans_country",
    "page_fans_locale",
    "page_fans",
  ],
  page_video_views: [
    "page_video_complete_views_30s_autoplayed",
    "page_video_complete_views_30s_click_to_play",
    "page_video_complete_views_30s_organic",
    "page_video_complete_views_30s_paid",
    "page_video_complete_views_30s_repeat_views",
    "page_video_complete_views_30s_unique",
    "page_video_complete_views_30s",
    "page_video_repeat_views",
    "page_video_view_time",
    "page_video_views_autoplayed",
    "page_video_views_by_paid_non_paid",
    "page_video_views_by_uploaded_hosted",
    "page_video_views_click_to_play",
    "page_video_views_organic",
    "page_video_views_paid",
    "page_video_views_unique",
    "page_video_views",
  ],
};

export const PAGE_MODELS_CONFIG: MODELS_CONFIG = {
  page_insights: {
    edge: ["insights"],
    fields: [
      ...PAGE_METRICS.page_cta_clicks,
      ...PAGE_METRICS.page_engagements,
      ...PAGE_METRICS.page_impressions,
      ...PAGE_METRICS.page_posts,
      ...PAGE_METRICS.page_reactions,
      ...PAGE_METRICS.page_user_demographic,
      ...PAGE_METRICS.page_video_views,
    ],
    fields_type: "metric",
    params_config: {
      period:"day"
    },
  },
  page_posts: {
    edge:[ "feed"],
    fields: ["id", "message", "created_time", "permalink_url"],
    fields_type: "fields",
    dependencies: ["post_insights"],
  },
};
