name: Cloud Run

on:
  push:
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  IMAGE: us-docker.pkg.dev/${{secrets.PROJECT_ID}}/us.gcr.io/${{ github.event.repository.name }}:${{ github.ref_name }}

  SERVICE: ${{ github.event.repository.name }}-${{ github.ref_name }}
  PUBLIC_URL: https://${{ github.event.repository.name }}-${{ github.ref_name }}-${{secrets.CLOUDRUN_CODE}}-uc.a.run.app

  REGION: us-central1
  GCP_SA: chienle-sa@${{secrets.PROJECT_ID}}.iam.gserviceaccount.com

  ENV_FILE: env.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > ${{ env.ENV_FILE }}
          echo "PUBLIC_URL: '${{env.PUBLIC_URL}}'" >> ${{ env.ENV_FILE }}

      - run: >-
          gcloud run deploy ${{ env.SERVICE }}
          --image=${{ env.IMAGE }}
          --memory=8Gi
          --cpu=2
          --platform=managed
          --service-account=${{ env.GCP_SA }}
          --region=${{ env.REGION }}
          --timeout=3500
          --env-vars-file=${{ env.ENV_FILE }}
          --allow-unauthenticated
          --labels run-service-id=${{ env.SERVICE }}
